version: 1

update_configs:

  - package_manager: "javascript"
    directory: "/"
    update_schedule: "live"
    default_reviewers:
      - ArtemFrantsiian
      - ni3gavhane

  - package_manager: "javascript"
    directory: "/packages/core"
    update_schedule: "live"
    default_reviewers:
      - ArtemFrantsiian
      - ni3gavhane
